name: CI/CD Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          
      - name: Build with Maven
        working-directory: DevOpsSummative2
        run: mvn clean package

      - name: Upload JAR to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.BP02388913_SECRET_ACCESS_KEY_ID }}
          source: "DevOpsSummative2/target/*.jar"
          target: "/home/ubuntu/"

      - name: Run JAR on EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.BP02388913_SECRET_ACCESS_KEY_ID }}
          script: |
            sudo apt update -y
            sudo apt install default-jre -y
            screen -dmS springboot java -jar *.jar
